name: Docker Image CI

on:
  push:
    branches: [ exam ]
  pull_request:
    branches: [ exam ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag abizera/e-seller:$(date +%s)
